#!/bin/bash

clear

#Kuvab esialgu 3 valikut nin kirjutab kasutajale, et ta valiks numbri"

osch=0
echo "1) liha ja karutlid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"
echo "Tee oma valik (1 või 2 või 3) : "
read osch

#Kui valik tehtud kuvab vastavalt numbrile vastava vastuse"

if [ $osch -eq 1 ] ; then
	echo "Väga maitsev, aga jälgi oma tervist!
	Head isu!"
else
	if [ $osch -eq 2 ] ; then
		echo "Brititoit on maitsev
	Head isu!"
else
		if [ $osch -eq 3 ] ; then
			echo "Nii tervislik ja igav
		Head isu!"
		fi
	fi
fi

